### ISSUE TITLE
How to add text labels.

### ISSUE THREAD

**Issue by NMC-DAVE** [flopp/py-staticmaps#10]
I want add text labels over map. How can I do? Very thanks!

**Comment by flopp** [comment]
Not yet, unfortunately :(

I guess I will have to restructure the code to make add custom markers (such as text labels) easier.

**Comment by NMC-DAVE** [comment]
Thanks very much. Looking forward to the new feature.

**Comment by flopp** [comment]
Have a look at `examples/custom_objects.py` for an example which adds custom text labels. Rendering SVG is a bit difficult, as there seem's to be no way of determining the text extents (text width + height) - so I'm guessing the extents...
