### ISSUE TITLE
Add docstrings for all public functions

### ISSUE THREAD

**Issue by flopp** [flopp/py-staticmaps#3]
n/a

**Comment by lowtower** [comment]
Which docstring format do You prefer?
[Google, numpy, reST/sphinx](https://stackoverflow.com/questions/3898572/what-is-the-standard-python-docstring-format#24385103) ?

**Comment by flopp** [comment]
I have no preference. What do you think?

**Comment by lowtower** [comment]
It seems like reST is the defacto standard, but I don't really have a preference.

**Comment by flopp** [comment]
So, let's go for reST!

**Comment by lowtower** [comment]
Just realized that You have used google style in GpxTrackPoster.
Still reST or better switch to google style to be consistent throughout Your projects?
